### ISSUE TITLE
Balancing problem

### ISSUE THREAD

**Issue by Demir42** [qassim-alwasti/ltc6803#1]
Hi im newbie on github. Im not sure about "issues" is right place for questions. If it isn't, im sorry about that. Whatever im working on electric vehicles research and development. I trying build a bms for 14 cells with your library. I have two pieces ltc6803-2 and working in the form of 7+7 for 14 cells. I build the bms with current protection+can-bus communication,+tempretature protection for every cells.

Everything works fine with my arduino code but when cells on charge and reach over voltage limit, its showing funny values  on serial monitor like 4.50v, 4.30v.  and its continously changing like beetwen 4.30v-3.78v. you can think like analog noise. i cut off charge and its still showing noisy values until reach over voltage limit. I dont know my code method is right for adding multi spi devices but i tried with standalone ltc6803. it still makes noisy values when reaches ov limit. How we can fix this issue? (Sorry for bad english.)

Here is my bms code. Im using it with mega2560. MCP2515 for can-bus, INA219 for current measuring, ds18b20 for temp sensing.

`#include <SPI.h>
#include <LTC6803.h>
#include <mcp2515.h>
#include <OneWire.h>
#include <DallasTemperature.h>
#include <Wire.h>
#include <Arduino.h>
#include <ErriezINA219.h>

#define PIN_RELAY_1 7 //for protection high amp contactor//
#define INA219_I2C_ADDRESS      0x40
#define INA219_SHUNT_RESISTOR   0.0003

ltc6803 ltc_A, ltc_B;

int chipSelect_A = 48;
int chipSelect_B = 49;

float uv_limit = 3.2;
float ov_limit = 4.2;
int cellNumber = 7;

int topvolt;
int perc;
float totalVoltage;
int current = 0;

int a;
int b;
int c;
int d;
int e;

struct can_frame canMsg1;
MCP2515 mcp2515(10);

OneWire oneWire(4);
DallasTemperature DS18B20(&oneWire);

DeviceAddress DS18B20adres0, DS18B20adres1, DS18B20adres2, DS18B20adres3, DS18B20adres4, DS18B20adres5, DS18B20adres6, DS18B20adres7, DS18B20adres8, DS18B20adres9, DS18B20adres10, DS18B20adres11, DS18B20adres12, DS18B20adres13, DS18B20adres14;

INA219 ina219 = INA219(INA219_I2C_ADDRESS, INA219_SHUNT_RESISTOR);

void setup() {

  Serial.begin(115200);
  ltc_A.begin(chipSelect_A, cellNumber, uv_limit, ov_limit);
  ltc_B.begin(chipSelect_B, cellNumber, uv_limit, ov_limit);
  DS18B20.begin();
  Wire.begin();
  Wire.setClock(400000);
  ina219.begin();
  
  mcp2515.reset();
  mcp2515.setBitrate(CAN_500KBPS);
  mcp2515.setNormalMode();
  
  pinMode(PIN_RELAY_1, OUTPUT);

  DS18B20.getAddress(DS18B20adres0, 0);
  DS18B20.getAddress(DS18B20adres1, 1);
  DS18B20.getAddress(DS18B20adres2, 2);
  DS18B20.getAddress(DS18B20adres3, 3);
  DS18B20.getAddress(DS18B20adres4, 4);
  DS18B20.getAddress(DS18B20adres5, 5);
  DS18B20.getAddress(DS18B20adres6, 6);
  DS18B20.getAddress(DS18B20adres7, 7);
  DS18B20.getAddress(DS18B20adres8, 8);
  DS18B20.getAddress(DS18B20adres9, 9);
  DS18B20.getAddress(DS18B20adres10, 10);
  DS18B20.getAddress(DS18B20adres11, 11);
  DS18B20.getAddress(DS18B20adres12, 12);
  DS18B20.getAddress(DS18B20adres13, 13);
  DS18B20.getAddress(DS18B20adres14, 14);

  DS18B20.setResolution(DS18B20adres0, 12);
  DS18B20.setResolution(DS18B20adres1, 12);
  DS18B20.setResolution(DS18B20adres2, 12);
  DS18B20.setResolution(DS18B20adres3, 12);
  DS18B20.setResolution(DS18B20adres4, 12);
  DS18B20.setResolution(DS18B20adres5, 12);
  DS18B20.setResolution(DS18B20adres6, 12);
  DS18B20.setResolution(DS18B20adres7, 12);
  DS18B20.setResolution(DS18B20adres8, 12);
  DS18B20.setResolution(DS18B20adres9, 12);
  DS18B20.setResolution(DS18B20adres10, 12);
  DS18B20.setResolution(DS18B20adres11, 12);
  DS18B20.setResolution(DS18B20adres12, 12);
  DS18B20.setResolution(DS18B20adres13, 12);
  DS18B20.setResolution(DS18B20adres14, 12);

  delay(500);
}

void loop() {
  
  ltc_A.getData();
  ltc_B.getData();

  totalVoltage = ltc_A.cell_voltages[0] + ltc_A.cell_voltages[1] + ltc_A.cell_voltages[2] + ltc_A.cell_voltages[3] + ltc_A.cell_voltages[4] + ltc_A.cell_voltages[5] + ltc_A.cell_voltages[6] + ltc_B.cell_voltages[0] + ltc_B.cell_voltages[1] + ltc_B.cell_voltages[2] + ltc_B.cell_voltages[3] + ltc_B.cell_voltages[4] + ltc_B.cell_voltages[5] + ltc_B.cell_voltages[6];
  
  ina219.read();
  
  topvolt = totalVoltage * 100;
  current = ina219.current / 1000;
  perc = map(topvolt, 4480, 5740, 0, 100); //calculating battery percentage//

  DS18B20.requestTemperatures();

  int myArray1[15] = {DS18B20.getTempC(DS18B20adres0), DS18B20.getTempC(DS18B20adres1), DS18B20.getTempC(DS18B20adres2), DS18B20.getTempC(DS18B20adres3), DS18B20.getTempC(DS18B20adres4), DS18B20.getTempC(DS18B20adres5), DS18B20.getTempC(DS18B20adres6), DS18B20.getTempC(DS18B20adres7), DS18B20.getTempC(DS18B20adres8), DS18B20.getTempC(DS18B20adres9), DS18B20.getTempC(DS18B20adres10), DS18B20.getTempC(DS18B20adres11), DS18B20.getTempC(DS18B20adres12), DS18B20.getTempC(DS18B20adres13), DS18B20.getTempC(DS18B20adres14)};
  int maxVal1 = myArray1[0];
  
   for (int i = 0; i < (sizeof(myArray1) / sizeof(myArray1[0])); i++) {
      maxVal1 = max(myArray1[i],maxVal1);//finding max value beetween battery cells temp sensors for sending with can-bus//
   }

  int myArray2[14] = {ltc_A.cell_voltages[0] * 100, ltc_A.cell_voltages[1] * 100, ltc_A.cell_voltages[2] * 100, ltc_A.cell_voltages[3] * 100, ltc_A.cell_voltages[4] * 100, ltc_A.cell_voltages[5] * 100, ltc_A.cell_voltages[6] * 100, ltc_B.cell_voltages[0] * 100, ltc_B.cell_voltages[1] * 100, ltc_B.cell_voltages[2] * 100, ltc_B.cell_voltages[3] * 100, ltc_B.cell_voltages[4] * 100, ltc_B.cell_voltages[5] * 100, ltc_B.cell_voltages[6] * 100};
  int maxVal2 = myArray2[0];
  int minVal2 = myArray2[0];
  
   for (int i = 0; i < (sizeof(myArray2) / sizeof(myArray2[0])); i++) {
      maxVal2 = max(myArray2[i],maxVal2);
      minVal2 = min(myArray2[i],minVal2);//finding max and min value beetween battery cells volts for sending with can-bus//
   }

  Serial.print("%");
  Serial.println(perc);
  Serial.println(totalVoltage);
  Serial.println(DS18B20.getTempC(DS18B20adres14));
  Serial.println(current);
  Serial.println("------------");

  Serial.print(ltc_A.cell_voltages[0]);
  Serial.print(" ");
  Serial.println(DS18B20.getTempC(DS18B20adres0));
  Serial.print(ltc_A.cell_voltages[1]);
  Serial.print(" ");
  Serial.println(DS18B20.getTempC(DS18B20adres1));
  Serial.print(ltc_A.cell_voltages[2]);
  Serial.print(" ");
  Serial.println(DS18B20.getTempC(DS18B20adres2));
  Serial.print(ltc_A.cell_voltages[3]);
  Serial.print(" ");
  Serial.println(DS18B20.getTempC(DS18B20adres3));
  Serial.print(ltc_A.cell_voltages[4]);
  Serial.print(" ");
  Serial.println(DS18B20.getTempC(DS18B20adres4));
  Serial.print(ltc_A.cell_voltages[5]);
  Serial.print(" ");
  Serial.println(DS18B20.getTempC(DS18B20adres5));
  Serial.print(ltc_A.cell_voltages[6]);
  Serial.print(" ");
  Serial.println(DS18B20.getTempC(DS18B20adres6));

  Serial.print(ltc_B.cell_voltages[0]);
  Serial.print(" ");
  Serial.println(DS18B20.getTempC(DS18B20adres7));
  Serial.print(ltc_B.cell_voltages[1]);
  Serial.print(" ");
  Serial.println(DS18B20.getTempC(DS18B20adres8));
  Serial.print(ltc_B.cell_voltages[2]);
  Serial.print(" ");
  Serial.println(DS18B20.getTempC(DS18B20adres9));
  Serial.print(ltc_B.cell_voltages[3]);
  Serial.print(" ");
  Serial.println(DS18B20.getTempC(DS18B20adres10));
  Serial.print(ltc_B.cell_voltages[4]);
  Serial.print(" ");
  Serial.println(DS18B20.getTempC(DS18B20adres11));
  Serial.print(ltc_B.cell_voltages[5]);
  Serial.print(" ");
  Serial.println(DS18B20.getTempC(DS18B20adres12));
  Serial.print(ltc_B.cell_voltages[6]);
  Serial.print(" ");
  Serial.println(DS18B20.getTempC(DS18B20adres13));

  Serial.println("*********");
  
  if (current > 300) {
    
    digitalWrite(PIN_RELAY_1, LOW);
    delay(10000);
  } 

  else {
    digitalWrite(PIN_RELAY_1, HIGH);

  } //current limiting//

 
  if (DS18B20.getTempC(DS18B20adres0) > 50 || DS18B20.getTempC(DS18B20adres1) > 50 || DS18B20.getTempC(DS18B20adres2) > 50 || DS18B20.getTempC(DS18B20adres3) > 50 || DS18B20.getTempC(DS18B20adres4) > 50 || DS18B20.getTempC(DS18B20adres5) > 50 || DS18B20.getTempC(DS18B20adres6) > 50 || DS18B20.getTempC(DS18B20adres7) > 50 || DS18B20.getTempC(DS18B20adres8) > 50 || DS18B20.getTempC(DS18B20adres9) > 50 || DS18B20.getTempC(DS18B20adres10) > 50 || DS18B20.getTempC(DS18B20adres11) > 50 || DS18B20.getTempC(DS18B20adres12) > 50 || DS18B20.getTempC(DS18B20adres13) > 50 || DS18B20.getTempC(DS18B20adres14) > 50) {
    digitalWrite(PIN_RELAY_1, LOW);
    delay(10000);
  } //temprature limiting//
  
  a = map(topvolt, 4480, 5740, 0, 255);
  b = map(maxVal1, 20, 80, 0, 255);
  c = map(current, -200, 300, 0, 255); 
  d = map(maxVal2, 320, 440, 0, 255);
  e = map(minVal2, 320, 440, 0, 255); //can-bus sends only numbers beetween 0-255 and i mapped values beetween 0-255//
  
  canMsg1.can_id  = 0x12;
  canMsg1.can_dlc = 5;

  canMsg1.data[0] = (a);
  canMsg1.data[1] = (b);
  canMsg1.data[2] = (c);
  canMsg1.data[3] = (d);
  canMsg1.data[4] = (e);
  
  mcp2515.sendMessage(&canMsg1);
  
  ltc_A.getData();
  ltc_B.getData(); // i know this is second time added this but can-bus glitches spi communication what comes after it. if i delete this getdata codes can-bus will freeze ltc_A ic. its works fine with this now.//
}`

**Comment by achmad0102** [comment]
hello demir do you have email ?, i want to ask about your ltc & voltage measurement projects, thx

**Comment by qassim-alwasti** [comment]
Hi @Demir42,
I believe it would be better to post this kind of requests\issues on Arduino forums to get better support from the community. 
Since the issue you're describing only happens when OV limit is reached, I would guess that activating the balancing cuircuit at OV is causing this drop\raise of measured cell voltages. You may try measuring while the balacing circuit is disconnected to verify if it is the source of the issue. 
Thanks.

**Comment by Demir42** [comment]
> hello demir do you have email ?, i want to ask about your ltc & voltage measurement projects, thx

muhmusde99@hotmail.com
